spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  datasource:
    username: manideep
    password: password

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: swiftpay-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted-packages: "com.manideep.swiftpay.*"

  thread:
    virtual:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instances:
      prefer-ip-adress: true
      hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN

app:
  kafka:
    topics:
      order: order.events
      payment: payment.events
      refund: refund.events
      settlement: settlement.events

jwt:
  secret-key: thisisasamplesecretkeykindlydonotusethiskeyintheproductionenvironment1234
