server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftpay-merchant-db

jwt:
  secret-key: thisisasamplesecretkeykindlydonotusethiskeyintheproductionenvironment1234

webhook:
  secret-encryption-key: JNWJEGfgNPwSw2e19NXuabjOJUKgi4hi2pqPq/stezY=
